export enum JobName {
  FIND_PROBLEM_MESSAGES = 'FIND_PROBLEM_MESSAGES',
  RESET_PROBLEM_MESSAGES = 'RESET_PROBLEM_MESSAGES',
  RESET_NULL_EVENT_TIMESTAMP_MESSAGES = 'RESET_NULL_EVENT_TIMESTAMP_MESSAGES',
}
