{
  "useCSRFProtection": true,
  "security": {
    "referrerPolicy": "origin"
  },
  "appInsights": {
    "instrumentationKey": false
  },
  "services": {
      "caseEventHandler": {
        "url": WA_CASE_EVENT_HANDLER_SERVICE_URL
      }
    }
}
